// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtAwChPnNFAWZV0l1sjueraaUYw7BUX_A',
    appId: '1:881152019942:web:a487bbe17e8be495721a27',
    messagingSenderId: '881152019942',
    projectId: 'switch-review-platform',
    authDomain: 'switch-review-platform.firebaseapp.com',
    storageBucket: 'switch-review-platform.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCMxT-1BiD1FE_NOe8YnBsfZhUvF_P2xA',
    appId: '1:881152019942:android:506ddf6cf4834047721a27',
    messagingSenderId: '881152019942',
    projectId: 'switch-review-platform',
    storageBucket: 'switch-review-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUuY7EiSV3i6p21qRM5glEtGFuPtOK3QI',
    appId: '1:881152019942:ios:76e5cc46332a2527721a27',
    messagingSenderId: '881152019942',
    projectId: 'switch-review-platform',
    storageBucket: 'switch-review-platform.appspot.com',
    iosBundleId: 'com.example.switchPlatform',
  );
}
